name: Conda CI

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - uses: mamba-org/setup-micromamba@v1
      with:
        generate-run-shell: true
        environment-name: test-env
        create-args: >-
          python=3.10
          pocl
          pyopencl
          scipy
          pytest
    - name: Test with pytest
      run: python -m pytest
      shell: micromamba-shell {0}
